### ISSUE TITLE
Bug: Doesnt work on windows?

### ISSUE THREAD

**Issue by amilajack** [sindresorhus/get-port-cli#3]
Would a PR to add appveyor support be welcome?

**Comment by sindresorhus** [comment]
> Doesnt work on windows?

Is this a question or a statement?

> Would a PR to add appveyor support be welcome?

No. I only add AppVeyor to large and popular projects as it's super annoying to setup and maintain.

**Comment by amilajack** [comment]
> Is this a question or a statement?

That was a question

**Comment by sindresorhus** [comment]
Yes, you can just assume anything in Node.js works on Windows unless written otherwise.
