### ISSUE TITLE
Get-port and system ports check

### ISSUE THREAD

**Issue by renjithspace** [sindresorhus/get-port-cli#9]
Hi @sindresorhus,

In the example port added in the `meow` usage is a system port 80.

I found the `get-port` library check only user and client ports starting from 1024 to 65535.

If so, do we need to update port 80 in the usage to a user or client port number?

https://github.com/sindresorhus/get-port-cli/blob/837beab41cef2b55722212605b25f981a8f288d4/cli.js#L17

**Comment by sindresorhus** [comment]
The example is meant to illustrate that it falls back to a different port if the wanted port is not available.

**Comment by renjithspace** [comment]
Got it. It makes sense.
